name: We Love Pasta
url: https://www.welovepasta.cr
description: "La mejor pasta de Escazú"
author: Awesome Inc
google_verification: oiWfM5jsdfyqs5o1ilQCfnM0raw6JPk
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
exclude: [node_modules]
collections:
    applications:
        output: true
        permalink: /applications/:path/
    interest:
        output: true
        permalink: /interest/:path/
    notes:
        output: true
        permalink: /notes/:path/
    courses:
        output: true
        permalink: /:path/
    tutorials:
        output: true
        permalink: /tutorials/:path/
